---
new_page_extension: md
auto_deploy: true
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: data/guests
  label: Guests
  create: all
  match: "**/*"
  new_doc_ext: toml
- type: directory
  path: content/episodes
  label: Episodes
  create: all
  match: "**/*"
upload_dir: ''
public_path: ''
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
version: '0.49'
