---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: data
  label: Data
  create: all
  match: '"*.toml"'
  new_doc_ext: '".toml"'
- type: directory
  path: content/episodes
  label: Episodes
  create: all
  match: "**/*"
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
version: '0.49'
